<?php

$livros = [
    ['id' => '1', 'titulo' => 'Harry Potter', 'autor' => 'J.K. Rowling', 'descricao' => 'Harry recebe uma carta misteriosa, entregue por uma coruja: um convite para estudar num lugar incrível chamado Escola de Magia e Bruxaria Hogwarts. Lá ele vai encontrar não só amigos, esportes praticados em vassouras voadoras e magia para todo lado.'],
    ['id' => '2', 'titulo' => 'As Sete Irmãs', 'autor' => 'Lucinda Riley', 'descricao' => 'Em As Sete Irmãs, Lucinda Riley inicia uma saga familiar de fôlego, que levará os leitores a diversos recantos e épocas e a viver amores impossíveis, sonhos grandiosos e surpresas emocionantes.'],
    ['id' => '3', 'titulo' => 'A Contadora', 'autor' => 'Freida McFadden', 'descricao' => 'A contadora é um thriller tenso e viciante da best-seller Freida McFadden, autora de A empregada, que explora a forma como segredos sombrios do passado podem ecoar no presente, com consequências fatais.'],
    ['id' => '4', 'titulo' => 'Mentes Perigosas', 'autor' => 'Ana Beatriz Barbosa Silva', 'descricao' => 'Em Mentes perigosas , a dra. Ana Beatriz Barbosa Silva revela esse sombrio transtorno de personalidade que atinge cerca de 4% da população mundial e mostra ao leitor como se prevenir contra as perversidades de uma mente psicopata.'],
    ['id' => '5', 'titulo' => 'Personalidades Perigosas', 'autor' => 'Joe Navarro e Toni Sciarra Poynter', 'descricao' => 'Nesta obra técnica e revolucionária, Navarro mergulha fundo na oratória e nas mentes perigosas oferecendo um estudo fascinante sobre todos os tipos de pessoas que lidamos em nosso dia a dia, em relações familiares, sociais e profissionais, além de ajudar a identificar sinais de alerta que muitas vezes passam despercebidos.'],
    ['id' => '6', 'titulo' => 'Gótico Mexicano', 'autor' => 'Silvia Moreno-Garcia', 'descricao' => 'A rotina de Noemí muda drasticamente quando seu pai recebe uma carta de sua prima Catalina, recém-casada com um inglês. A carta é, na verdade, um pedido desesperado de socorro, pois Catalina acredita que corre perigo em High Place, a mansão isolada onde vive confinada com o marido e a família dele.'],
    ['id' => '7', 'titulo' => 'A Seleção', 'autor' => 'Kiera Cass', 'descricao' => 'Muitas garotas sonham em ser princesas, mas este não é o caso de America Singer. Ela topa se inscrever na Seleção só para agradar a mãe, certa de que não será sorteada para participar da competição em que o príncipe escolherá sua futura esposa. '],
    ['id' => '8', 'titulo' => 'Pequenos Segredos', 'autor' => 'Jennifer Hillier', 'descricao' => 'Prepare-se para mergulhar em uma trama cheia de reviravoltas, na qual o perigo está à espreita em cada página e a busca pela verdade pode ter consequências devastadoras.'],
    ['id' => '9', 'titulo' => 'Tudo é Rio', 'autor' => 'Carla Madeira', 'descricao' => 'Com uma narrativa madura, precisa e ao mesmo tempo delicada e poética, o romance narra a história do casal Dalva e Venâncio, que tem a vida transformada após uma perda trágica.'],
];
